version: "3"
services:
    etcd:
        image: "bitnami/etcd:latest"
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
            - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
            - ETCDCTL_API=2
    nats:
        image: nats
    order-service:
        build:
            context: .
            dockerfile: order/service/Dockerfile
        image: docker.pkg.github.com/vesose/example-micro/order:latest
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
        command: --registry_address=etcd:2379 --broker_address=nats:4222
        depends_on:
            - etcd
            - shipment-service
            - stock-service
            - nats
    shipment-service:
        build:
            context: .
            dockerfile: shipment/service/Dockerfile
        image: docker.pkg.github.com/vesose/example-micro/shipment:latest
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
        command: --registry_address=etcd:2379
        depends_on:
            - etcd
            - stock-service
    stock-service:
        build:
            context: .
            dockerfile: stock/service/Dockerfile
        image: docker.pkg.github.com/vesose/example-micro/stock:latest
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
        command: --registry_address=etcd:2379 --broker_address=nats:4222
        depends_on:
            - etcd
            - nats
    payment-service:
        build:
            context: .
            dockerfile: payment/service/Dockerfile
        image: docker.pkg.github.com/vesose/example-micro/payment:latest
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
        command: --registry_address=etcd:2379
        depends_on:
            - etcd
    
    supplier-service:
        build:
            context: .
            dockerfile: supplier/service/Dockerfile
        image: docker.pkg.github.com/vesose/example-micro/supplier:latest
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
        command: --registry_address=etcd:2379
        depends_on:
            - etcd
            - stock-service
    client-service:
        build:
            context: .
            dockerfile: client-2/service/Dockerfile
        image: docker.pkg.github.com/vesose/example-micro/client-2:latest
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
        command: --registry_address=etcd:2379
        depends_on:
            - etcd
            - supplier-service
            - order-service
            - payment-service
    
    
